basePath: /
definitions:
  dto.ExampleResponse:
    properties:
      created_at:
        format: date-time
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updated_at:
        format: date-time
        type: string
    required:
    - name
    - price
    type: object
  response.Response:
    properties:
      data: {}
      error_data: {}
      message:
        type: string
      type:
        type: string
    type: object
host: localhost:9009
info:
  contact:
    email: tianrosandhy@gmail.com
    name: TianRosandhy
  description: Chatbot Expense
  title: Chatbot Expense
  version: 1.0.0
paths:
  /api/v1/example:
    get:
      description: Example of single handler / controller.
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ExampleResponse'
              type: object
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Example of single handler / controller.
      tags:
      - Examples
schemes:
- http
swagger: "2.0"
