basePath: /api/v1
definitions:
  dto.ExampleRequest:
    properties:
      name:
        type: string
      price:
        type: number
    required:
    - name
    - price
    type: object
  dto.ExampleResponse:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    required:
    - name
    - price
    type: object
  response.Response:
    properties:
      data: {}
      error_data: {}
      message:
        type: string
      type:
        type: string
    type: object
host: localhost
info:
  contact:
    email: tianrosandhy@gmail.com
    name: TianRosandhy
  description: Skeleton Service
  title: Skeleton Service
  version: 1.0.0
paths:
  /v1/example:
    get:
      description: Get list of example.
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.ExampleResponse'
                  type: array
              type: object
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get list of example.
      tags:
      - Examples
    post:
      description: Create new example data.
      parameters:
      - description: Example request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.ExampleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ExampleResponse'
              type: object
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Create new example data.
      tags:
      - Examples
  /v1/example/{id}:
    delete:
      description: Get single example.
      parameters:
      - description: Example ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get single example.
      tags:
      - Examples
    get:
      description: Get single example.
      parameters:
      - description: Example ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ExampleResponse'
              type: object
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get single example.
      tags:
      - Examples
    patch:
      description: Update existing example data
      parameters:
      - description: Example request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.ExampleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ExampleResponse'
              type: object
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Update existing example data
      tags:
      - Examples
schemes:
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
